Trello/urls.py
from django.contrib import admin
from django.urls import path, include
from category.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('category.urls')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

category/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_views

app_name = "category"

urlpatterns = [
	path('', HomePageView.as_view(), name="home"),
	path('signup/', Signup.as_view(), name='signup'),
]

category/models.py
from django.db import models

class Task(models.Model):
    title = models.CharField(max_length=30, blank=True, null=True)
    description = models.CharField(max_length=512, blank=True, null=True)

class Category(models.Model):
    category = models.CharField(max_length=30, blank=True, null=True)
    Task = models.ForeignKey(Task, on_delete=models.CASCADE, null=True, blank=True)

category/forms.py
from django import forms
from django.contrib.auth.models import User, Group
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate, login
import re
from django.contrib.auth.forms import PasswordChangeForm


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100,
               widget= forms.TextInput
               (attrs=
               	{'class':'form-control',
				'id':'username',
				'placeholder': 'User Name',
				}))
    password = forms.CharField(max_length=100,
               widget=forms.PasswordInput
               (attrs=
               	{'class':'form-control',
				'id':'password',
				'placeholder': 'Password',
				}))

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user is None:
            raise ValidationError("Please enter valid Username & Password")
        return self.cleaned_data

class DummyForm(forms.Form):
  pass

class SignupForm(forms.Form):
    username = forms.CharField(max_length=20,
               widget= forms.TextInput
               (attrs=
                {'class':'form-control',
                'id':'username',
                'placeholder': 'User Name',
                }))
    email_id = forms.EmailField(max_length=64,
               widget= forms.EmailInput
               (attrs=
                {'class':'form-control',
                'id':'email_id',
                'placeholder': 'Email ID',
                }))
    password = forms.CharField(max_length=20,
               widget=forms.PasswordInput
               (attrs=
                {'class':'form-control',
                'id':'password',
                'placeholder': 'Password',
                }))
    reenter_password = forms.CharField(max_length=20,
               widget=forms.PasswordInput
               (attrs=
                {'class':'form-control',
                'id':'reenter_password',
                'placeholder': 'Re-Enter Password',
                }))

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            user = User.objects.get(username=username)
        except Exception:
            user = None
        if user is not None:
            raise ValidationError("Username Already Exists.")
        return username

    def clean_reenter_password(self):
        password = self.cleaned_data['password']
        reenter_password = self.cleaned_data['reenter_password']
        if password != reenter_password:
            raise ValidationError("Password and Re-Enter didn't match")

        return reenter_password

    def save(self):
        user = User()
        user.username = self.cleaned_data['username']
        user.email = self.cleaned_data['email_id']
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user

category/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Permission, User
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView
from django.views.generic import TemplateView
from .forms import *
from .models import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse


class LoginView(FormView): 
    form_class = LoginForm
    template_name = "login.html"
    success_url ="/"

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(self.request, user)
        return HttpResponseRedirect(self.get_success_url())

@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/login/')


class HomePageView(LoginRequiredMixin, FormView):
    form_class = DummyForm
    template_name = "home.html"
    success_url ="/"

    def get_context_data(self, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        return kwargs

    def post(self, request, *args, **kwargs):
        return HttpResponseRedirect(self.get_success_url())


class Signup(FormView):
    form_class = SignupForm
    template_name = "signup.html"
    success_url = "/login/"

    def get_context_data(self, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        return kwargs

    def form_valid(self, form):
        user_obj = form.save()
        return super(Signup, self).form_valid(form)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}
  <title>Trello</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style type="text/css">
    #username{
      width: 400px;
    }
    #password{
      width: 400px;
    }
    #reenter_password{
      width: 400px;
    }
    #email_id{
      width: 400px;
    }
    #id_old_password{
      width: 400px;
    }
    #id_new_password1{
      width: 400px;
    }
    #id_new_password2{
      width: 400px;
    }
    body{
      font-size: 16px;
    }
    #serial-number-input {
      width: 100%; /* Full-width */
      font-size: 16px; /* Increase font-size */
      padding: 12px 20px 12px 12px; /* Add some padding */
      border: 0.8px solid black; /* Add a grey border #ddd or black*/
      margin-bottom: 12px; /* Add some space below the input */
    }

    .search-list-btn {
      width: 100%;
      font-size: 16px;
      text-align: left;
      padding: 12px 20px 12px 12px;
      border-radius: 10px/100px;
      border-top-left-radius: 0;
      border-bottom-left-radius: 0;
      border-top-right-radius: 0;
      border-bottom-right-radius: 0;
    }
    .search-list-btn:hover {
      background-color: #d3d0d0;
    }
  </style>
  {% endblock %}
</head>
<body onload="load()">
  {% block navbar %}
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'category:home' %}" style="color: white;font-size: 24px;">Trello</a>
      </div>
      
      {% if request.user.is_authenticated %}
        <ul class="nav navbar-nav navbar-right">
          <li style="color: white; padding: 13px 0px 13px 0px;">Hi, {{request.user.username}} |</li>
          <li>
            <div class="dropdown" style="padding: 10px;">
              <button class="btn dropdown-toggle" type="button" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span>
              <span class="caret"></span></button>
              <ul class="dropdown-menu">
                <li><a href="{% url 'logout' %}">Logout</a></li>
              </ul>
            </div>
          </li>
        </ul>
      {% else %}
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'category:signup' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        </ul>

      {% endif %}
    </div>
  </nav>
  <div style="padding-bottom: 65px;"></div>
  {% endblock %}

  {% block content %}
  {% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}

templates/login.html
{% extends 'base.html' %}

<style type="text/css">
	#username{
		width: 400px;
	}
</style>

{% block content %}
  <div class="container">
  	<center>
	    <img src="/media/trello-logo-blue.svg" alt="Trello Logo" width="250px" style="padding-top: 100px;">
	    <form method="POST">{% csrf_token %}
		    <div class="form-group">
		      {{ form.username }}
		    </div>
		    <div class="form-group">
		      {{ form.password }}
		    </div>
		    {% if form.errors %}
		    <div class="alert alert-danger" style="width: 400px;">
		       Please enter valid <strong>Username & Passoword</strong>
		    </div>
		    {% endif %}
		    <button type="submit" class="btn btn-success" style="width: 400px;padding:10px;">Login</button>
		</form>
	</center>
  </div>

{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
	<h2 style="padding-left: 140px;">SignUp</h2>
    <form method="POST" id="CreateUserForm">{% csrf_token %}
	    <div class="form-group">
	      {{ form.username }}
	    </div>
	    {% if form.username.errors %}
		    <div class="alert alert-danger" style="width: 400px;">
		       {{form.username.errors}}
		    </div>
	    {% endif %}
	    <div class="form-group">
	      {{ form.email_id }}
	    </div>
        {% if form.email_id.errors %}
    	    <div class="alert alert-danger" style="width: 400px;">
    	       {{form.email_id.errors}}
    	    </div>
        {% endif %}
	    <div class="form-group">
	      {{ form.password }}
	    </div>
        {% if form.password.errors %}
    	    <div class="alert alert-danger" style="width: 400px;">
    	       {{form.password.errors}}
    	    </div>
        {% endif %}
	    <div class="form-group">
	      {{ form.reenter_password }}
	    </div>
        {% if form.reenter_password.errors %}
    	    <div class="alert alert-danger" style="width: 400px;">
    	       {{form.reenter_password.errors}}
    	    </div>
        {% endif %}
	    <button type="submit" class="btn btn-success" style="width: 400px;padding:10px;">SignUp</button>
	</form>
</div>

{% endblock %}